### ISSUE TITLE
chat detection in AFK warden app

### ISSUE THREAD

**Issue by diablo-N** [nandofw/Linux-Alt1-Toolkit#10]
i cant get chat detection in afk warden to work it finds the chat but detects only part of text and adinng som wierd symbols to it is it buged in current release or do i have something setup incorectly?
running latest release of majaro.
ps sorry for bad english

**Comment by nandofw** [comment]
the chat detection not work at all because the OCR is not fully implemented and is hard to make it work properly without the original source code.

**Comment by diablo-N** [comment]
ok thanx
