### ISSUE TITLE
White screen in toolkit on all apps

### ISSUE THREAD

**Issue by pekempy** [nandofw/Linux-Alt1-Toolkit#11]
`[pekempy@linux alt-1-toolkit]$ sudo sh alt1run.sh    
LaunchProcess: failed to execvp:    
/run/media/pekempy/4TB/Documents/alt-1-toolkit/subproces    
LaunchProcess: failed to execvp:    
/run/media/pekempy/4TB/Documents/alt-1-toolkit/subproces    
LaunchProcess: failed to execvp:    
/run/media/pekempy/4TB/Documents/alt-1-toolkit/subproces    
65    
12    
LaunchProcess: failed to execvp:    
/run/media/pekempy/4TB/Documents/alt-1-toolkit/subproces       
` 

Above is the terminal output for alt1 when I run it.
Arch linux
https://i.imgur.com/jI5D1HI.png

**Comment by nandofw** [comment]
Maybe a permission issue. Check that the file 'alt1linux' and 'subproces' are allowed to run
