### ISSUE TITLE
Not detecting compass clues

### ISSUE THREAD

**Issue by pekempy** [nandofw/Linux-Alt1-Toolkit#3]
Thanks for this, very helpful and tempting to get me to move over to Linux full time.

Trying to get through my backlog of clues, and it seems no matter what it's not picking up my compass clues. 

Running Arch Linux. Other clues seem to detect ok, such as puzzle clues

**Comment by nandofw** [comment]
Hello, thanks for replying.

First: this version does not have any automation. so you should inform the app of your current position manually by double-clicking on the map, then clicking to search for the compass clue.

pd1: I am currently using desktop capture that can lead to problems with the colors, and this can cause problems with the detection.
pd2: The next release will come with a new capture system based on xlib and a fully rewritten overlay system.
pd3: I made one elite clue and the compass has working normally on my system.

regards.
