### ISSUE TITLE
Problemas compilando/executando

### ISSUE THREAD

**Issue by FranciscoKnebel** [nandofw/Linux-Alt1-Toolkit#4]
Olá Fernando, estava procurando um port do Alt1, bacana ver programas brasileiros!

Achei um pouco confuso as explicações nas outras issues, não descobri como usar a aplicação. Tentei seguir as instruções de build que estava na outra issue. Baixei as dependências de Pascal que foram pedidas, mas não descobri como executar/compilar com as instruções que encontrei.
Poderia adicionar uma lista de passo-a-passo ou já gerar um binário com o programa executável?

**Comment by nandofw** [comment]
Olá Francisco, na seçao releases estão disponivel os binarios compilados com as dependencias incluidas. Para rodar basta descompactar e executar o arquivo .sh (pode ser nesesario dar permições).
Como sou pesimo para explicar vou deixar a parte de compilar com o google mesmo, procure tutoriais de como usar o lazarus, compilar e instalar dependencias nele.
