### ISSUE TITLE
Fish Flingers App

### ISSUE THREAD

**Issue by VonWernerGH** [nandofw/Linux-Alt1-Toolkit#6]
Hi,

First and foremost, thank you very much for your effort in making an alternative for Linux of "Alt1".
Second, ask you to include the "Fish Flingers" application at the end of the request queue.

Thank you so much.

**Comment by nandofw** [comment]
Hi,

You can add apps editing the apps.json file.

Regards.

**Comment by VonWernerGH** [comment]
Thanks, Editited and working :).
