### ISSUE TITLE
EOSError

### ISSUE THREAD

**Issue by VonWernerGH** [nandofw/Linux-Alt1-Toolkit#8]
Ay idea about this:

user@localhost:release$ ./alt1run.sh 
[FORMS.PP] ExceptionOccurred 
  Sender=EOSError
  Exception=An operating system call failed.
  Stack trace:
  $00000000004E3A5E
  $00000000004E3971
TApplication.HandleException An operating system call failed.
  Stack trace:
  $00000000004E3A5E
  $00000000004E3971
Exception at 00000000004E3A5E: EOSError:
An operating system call failed.

I'm using Mageia 7.1, i was using Mageia 5, i upgrade my system and keep my home directory, In Mageia 5 all was working ok,

Von.

**Comment by nandofw** [comment]
Hi,
Not know exactly what is the error but probable a missing or updated library.
You can check if any library is missing with  `ldd ./alt1linux` in terminal and compare with this list:

```
        linux-vdso.so.1 
	libX11.so.6 
	libXcomposite.so.1 
	libXext.so.6
	libXfixes.so.3 
	libpthread.so.0 
	libdl.so.2 
	libgdk-x11-2.0.so.0
	libgdk_pixbuf-2.0.so.0
	libgtk-x11-2.0.so.0 
	libgobject-2.0.so.0 
	libglib-2.0.so.0 
	libgthread-2.0.so.0 
	libgmodule-2.0.so.0 
	libpango-1.0.so.0 
	libcairo.so.2 
	libatk-1.0.so.0 
	libc.so.6 
	libxcb.so.1 
	/lib64/ld-linux-x86-64.so.2
	libpangocairo-1.0.so.0 
	libgio-2.0.so.0
	libfontconfig.so.1 
	libXrender.so.1
	libXinerama.so.1 
	libXi.so.6 
	libXrandr.so.2 
	libXcursor.so.1 
	libXdamage.so.1 
	libm.so.6 
	libpangoft2-1.0.so.0 
	libffi.so.6 
	libpcre.so.3 
	libthai.so.0 
	libpixman-1.so.0 
	libfreetype.so.6 
	libpng12.so.0 
	libxcb-shm.so.0 
	libxcb-render.so.0 
	libz.so.1 
	librt.so.1 
	libXau.so.6 
	libXdmcp.so.6 
	libselinux.so.1 
	libresolv.so.2 
	libexpat.so.1 
	libharfbuzz.so.0 
	libdatrie.so.1 
	libgraphite2.so.3
```
Another possibility is that the system not find the library libcef.so, in thi case one posible solution is move the file libcef.so to /usr/lib64
Regards

**Comment by VonWernerGH** [comment]
no idea what's happening.

When i run ldd ./alt1linux |grep -i "not"  all it's ok, no missing librarys.

Comparing ldd ./alt1linux from you system with mine i got next:

Mine <------------------> Yours
libpcre.so.1 <------> libpcre.so.3
libpng16.so.16 <------> libpng12.so.0
               <--------------->libselinux.so.1
libfribidi.so.0
libEGL.so.1
libGL.so.1
libmount.so.1
libxml2.so.2
libuuid.so.1 
libbz2.so.1 
libgbm.so.1
libglapi.so.0
libX11-xcb.so.1
libxcb-dri2.so.0
libxcb-xfixes.so.0
libdrm.so.2
libwayland-client.so.0
libwayland-server.so.0
libxcb-dri3.so.0
libxcb-present.so.0 
libxcb-sync.so.1
libxshmfence.so.1
libxcb-glx.so.0
libXxf86vm.so.1
libbsd.so.0
libblkid.so.1
liblzma.so.5

about the file libcef.so is not in my system, i install the package  syslog-ng that include it, i try making a symbolic link and later making a copy to /usr/lib64 but no better result.

Thanks for your  time and help.

Von.

**Comment by VonWernerGH** [comment]
Ups, i found the file libcef.so in alt1 directory, i copied  to /usr/lib64 and the same problem.

Von.

**Comment by VonWernerGH** [comment]
Ok, I have no idea why I stop booting alt1 on my computer, so i reinstall my system, install the nxt client, debug some things and now alt1 it's working again. I will be observing my changes so that if the problem arises again, I have a better idea of ​​what happens.

Von.

**Comment by VonWernerGH** [comment]
Hi again,

Well, the problem is here again, but this time i look for dependencys in libcef.so and i found this:

user@localhost:release$ ldd libcef.so |grep -i "no"
        libgconf-2.so.4 => not found

ok, know i know where the problem is i check from where libgconf-2.so.4 comes:

[root@localhost ~]# urpmf libgconf-2.so.4
lib64GConf2_4:/usr/lib64/libgconf-2.so.4.1.5
    $MIRRORLIST: media/core/updates/media_info/20191130-125445-files.xml.lzma
    $MIRRORLIST: media/nonfree/release/media_info/20190628-001219-files.xml.lzma                                                                    
    $MIRRORLIST: media/nonfree/updates/media_info/20191119-211043-files.xml.lzma                                                                    
    $MIRRORLIST: media/tainted/release/media_info/20190628-001348-files.xml.lzma                                                                    
    $MIRRORLIST: media/tainted/updates/media_info/20191023-203714-files.xml.lzma                                                                    
no hay xml-info para el soporte «google-chrome»

Ok i install lib64GConf2_4 and the problem was fixed :).

Von.
